package com.antilia.struts2.entities;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EmployeeRoleId generated by hbm2java
 */
@Embeddable
public class EmployeeRoleId implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	private long role;
	private long employee;

	public EmployeeRoleId() {
	}

	public EmployeeRoleId(long role, long employee) {
		this.role = role;
		this.employee = employee;
	}

	@Column(name = "role", nullable = false)
	public long getRole() {
		return this.role;
	}

	public void setRole(long role) {
		this.role = role;
	}

	@Column(name = "employee", nullable = false)
	public long getEmployee() {
		return this.employee;
	}

	public void setEmployee(long employee) {
		this.employee = employee;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EmployeeRoleId))
			return false;
		EmployeeRoleId castOther = (EmployeeRoleId) other;

		return (this.getRole() == castOther.getRole())
				&& (this.getEmployee() == castOther.getEmployee());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getRole();
		result = 37 * result + (int) this.getEmployee();
		return result;
	}

}
