package com.antilia.struts2.entities;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Task generated by hbm2java
 */
@Entity
@Table(name = "task")
public class Task implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "project", nullable = false)
	private Task task;
	
	@Column(name = "name", nullable = false, length = 200)
	private String name;
	
	@Column(name = "description", nullable = false, length = 400)
	private String description;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "startdate", nullable = false, length = 13)
	private Date startdate;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "enddate", length = 13)
	private Date enddate;
	
	@Column(name = "estimatedhours", precision = 3, scale = 1)
	private BigDecimal estimatedhours;
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "task")
	private Set<Asignment> asignments = new HashSet<Asignment>(0);
	
	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.LAZY, mappedBy = "task")
	private Set<Task> tasks = new HashSet<Task>(0);	

	public Task() {
	}

	public Task(long id, Task task, String name, String description,
			Date startdate) {
		this.id = id;
		this.task = task;
		this.name = name;
		this.description = description;
		this.startdate = startdate;
	}

	public Task(long id, Task task, String name, String description,
			Date startdate, Date enddate, BigDecimal estimatedhours,
			Set<Asignment> asignments, Set<Task> tasks) {
		this.id = id;
		this.task = task;
		this.name = name;
		this.description = description;
		this.startdate = startdate;
		this.enddate = enddate;
		this.estimatedhours = estimatedhours;
		this.asignments = asignments;
		this.tasks = tasks;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public Task getTask() {
		return this.task;
	}

	public void setTask(Task task) {
		this.task = task;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public Date getStartdate() {
		return this.startdate;
	}

	public void setStartdate(Date startdate) {
		this.startdate = startdate;
	}

	
	public Date getEnddate() {
		return this.enddate;
	}

	public void setEnddate(Date enddate) {
		this.enddate = enddate;
	}

	
	public BigDecimal getEstimatedhours() {
		return this.estimatedhours;
	}

	public void setEstimatedhours(BigDecimal estimatedhours) {
		this.estimatedhours = estimatedhours;
	}

	
	public Set<Asignment> getAsignments() {
		return this.asignments;
	}

	public void setAsignments(Set<Asignment> asignments) {
		this.asignments = asignments;
	}

	
	public Set<Task> getTasks() {
		return this.tasks;
	}

	public void setTasks(Set<Task> tasks) {
		this.tasks = tasks;
	}

}
