
connect 'jdbc:derby://localhost:1527/manager;create=true;user=reiern70;password=tetris11';

CREATE SCHEMA MANAGER;

SET SCHEMA MANAGER;

CREATE TABLE COUNTRY (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  name VARCHAR(300) NOT NULL,
  domain VARCHAR(3) NOT NULL
);

ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_PK PRIMARY KEY (ID);
ALTER TABLE COUNTRY ADD CONSTRAINT COUNTRY_NAME_UNIQ UNIQUE (name);


CREATE TABLE CITY (
  ID INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  COUNTRY INTEGER NOT NULL,
  NAME  VARCHAR(300) NOT NULL
);

ALTER TABLE CITY ADD CONSTRAINT CITY_PK PRIMARY KEY (ID);
ALTER TABLE CITY ADD CONSTRAINT CITY_NAME_COU_UNIQ UNIQUE (NAME, COUNTRY);
ALTER TABLE CITY ADD CONSTRAINT CITY_FK_COUNTRY FOREIGN KEY (COUNTRY) REFERENCES COUNTRY(ID) ON DELETE RESTRICT;

CREATE TABLE ADDRESS (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  city INTEGER  NOT NULL,
  address1 VARCHAR(300) NOT NULL,
  address2 VARCHAR(300) ,
  address3 VARCHAR(300),
  zipcode VARCHAR(40)
);

ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_PK PRIMARY KEY (ID);
ALTER TABLE ADDRESS ADD CONSTRAINT ADDRESS_FK_CITY FOREIGN KEY (CITY) REFERENCES CITY(ID) ON DELETE RESTRICT;

CREATE TABLE CUSTOMER (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  address INTEGER NOT NULL,
  name VARCHAR(500) NOT NULL,
  status VARCHAR(20)
);

ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_PK PRIMARY KEY (ID);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_NAME_ADD_UNIQ UNIQUE (NAME, ADDRESS);
ALTER TABLE CUSTOMER ADD CONSTRAINT CUSTOMER_FK_ADDRESS FOREIGN KEY (ADDRESS) REFERENCES ADDRESS(ID) ON DELETE RESTRICT;


CREATE TABLE EMPLOYEE (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  homeAddress INTEGER NOT NULL,
  name VARCHAR(100) NOT NULL,
  lastName1 VARCHAR(100) NOT NULL,
  lastName2 VARCHAR(100),
  hired DATE NOT NULL,
  fired DATE
);


ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (ID);
ALTER TABLE EMPLOYEE ADD CONSTRAINT EMPLOYEE_FK_ADDRESS FOREIGN KEY (homeAddress) REFERENCES ADDRESS(ID) ON DELETE RESTRICT;

CREATE TABLE ROLE (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  name VARCHAR(100) NOT NULL,
  shortdescription  VARCHAR(300) NOT NULL,
  description VARCHAR(2000)
);

ALTER TABLE ROLE ADD CONSTRAINT ROLE_PK PRIMARY KEY (ID);
ALTER TABLE ROLE ADD CONSTRAINT ROLE_NAME_UNIQ UNIQUE (NAME);


CREATE TABLE EMPLOYEE_ROLE (
  ROLE INTEGER NOT NULL,
  EMPLOYEE INTEGER NOT NULL,
  startDate DATE NOT NULL, 
  endDate DATE
);

ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT EMPLOYEE_ROLE_PK PRIMARY KEY (ROLE, EMPLOYEE);
ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT EMPLOYEE_ROLE_FK_EMPLOYEE FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE(ID) ON DELETE CASCADE;
ALTER TABLE EMPLOYEE_ROLE ADD CONSTRAINT EMPLOYEE_ROLE_FK_ROLE FOREIGN KEY (ROLE) REFERENCES ROLE(ID) ON DELETE RESTRICT;


CREATE TABLE PROJECT (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  customer INTEGER NOT NULL,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(500),
  startTime DATE NOT NULL,
  endTime DATE
);

ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_PK PRIMARY KEY (ID);
ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_NAME_CUST_UNIQ UNIQUE (NAME, CUSTOMER);
ALTER TABLE PROJECT ADD CONSTRAINT PROJECT_FK_CUSTOMER FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID) ON DELETE RESTRICT;


CREATE TABLE CHARGERATE (
    id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
    customer INTEGER NOT NULL,
    role INTEGER NOT NULL, 
    chargePerHour NUMERIC(3,2) DEFAULT 0
);

ALTER TABLE CHARGERATE ADD CONSTRAINT CHARGERATE_PK PRIMARY KEY (ID);
ALTER TABLE CHARGERATE ADD CONSTRAINT CHARGERATE_FK_CUSTOMER FOREIGN KEY (CUSTOMER) REFERENCES CUSTOMER(ID) ON DELETE RESTRICT;

CREATE TABLE TASK (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  project INTEGER NOT NULL,
  name VARCHAR(200) NOT NULL,
  description VARCHAR(400) NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE,
  estimatedHours NUMERIC(3,1)
);

ALTER TABLE TASK ADD CONSTRAINT TASK_PK PRIMARY KEY (ID);
ALTER TABLE TASK ADD CONSTRAINT TASK_FK_PROJECT FOREIGN KEY (PROJECT) REFERENCES TASK(ID) ON DELETE RESTRICT;


CREATE TABLE ASIGNMENT (
  id INTEGER NOT NULL generated always as identity (start with 1, increment by 1),
  task INTEGER NOT NULL,
  employee INTEGER NOT NULL,  
  startDate DATE NOT NULL,
  endDate DATE,
  estimatedHours NUMERIC(3,2)
);

ALTER TABLE ASIGNMENT ADD CONSTRAINT ASIGNMENT_PK PRIMARY KEY (ID);
ALTER TABLE ASIGNMENT ADD CONSTRAINT ASIGNMENT_TASK_EMP_UNIQ UNIQUE (TASK, EMPLOYEE);
ALTER TABLE ASIGNMENT ADD CONSTRAINT ASIGNMENT_FK_TASK FOREIGN KEY (TASK) REFERENCES TASK(ID) ON DELETE RESTRICT;
ALTER TABLE ASIGNMENT ADD CONSTRAINT ASIGNMENT_FK_EMPLOYEE FOREIGN KEY (EMPLOYEE) REFERENCES EMPLOYEE(ID) ON DELETE RESTRICT;


DROP SCHEMA MANAGER;DROP TABLE "MANAGER"."EMPLOYEE_ROLE";
DROP TABLE "MANAGER"."ROLE";
DROP TABLE "MANAGER"."ASIGNMENT";
DROP TABLE "MANAGER"."EMPLOYEE";
DROP TABLE "MANAGER"."CHARGERATE";
DROP TABLE "MANAGER"."PROJECT";
DROP TABLE "MANAGER"."CUSTOMER";
DROP TABLE "MANAGER"."TASK";
DROP TABLE "MANAGER"."ADDRESS";
DROP TABLE "MANAGER"."CITY";
DROP TABLE "MANAGER"."COUNTRY";

