package com.antilia.struts2.entities;

// Generated Apr 23, 2008 5:11:37 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Project generated by hbm2java
 */
@Entity
@Table(name = "project", uniqueConstraints = @UniqueConstraint(columnNames = {
		"name", "customer" }))
public class Project implements java.io.Serializable {
	
	private static final long serialVersionUID = 1L;
	
	@Id
	@Column(name = "id", unique = true, nullable = false)
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Long id;
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer", nullable = false)
	private Customer customer;
	
	@Column(name = "name", nullable = false, length = 200)
	private String name;
	
	@Column(name = "description", length = 500)
	private String description;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "starttime", nullable = false, length = 13)
	private Date starttime;
	
	@Temporal(TemporalType.DATE)
	@Column(name = "endtime", length = 13)
	private Date endtime;

	public Project() {
	}

	public Project(long id, Customer customer, String name, Date starttime) {
		this.id = id;
		this.customer = customer;
		this.name = name;
		this.starttime = starttime;
	}

	public Project(long id, Customer customer, String name, String description,
			Date starttime, Date endtime) {
		this.id = id;
		this.customer = customer;
		this.name = name;
		this.description = description;
		this.starttime = starttime;
		this.endtime = endtime;
	}

	
	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	
	public Date getStarttime() {
		return this.starttime;
	}

	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	
	public Date getEndtime() {
		return this.endtime;
	}

	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

}
